((emoji--command-Emoji nil)
 (emoji--command-Emoji\ >\ Body nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand\ >\ fingers-open nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand\ >\ fingers-open\ 👋 nil)
 (emoji--command-Emoji\ >\ People nil)
 (emoji--command-Emoji\ >\ People\ >\ role nil)
 (emoji--command-Emoji\ >\ People\ >\ role\ 🧑‍⚖️ nil)
 (emoji--command-Emoji\ >\ People\ >\ role\ 🧑‍💻 nil)
 (emoji--command-Emoji\ >\ Smileys nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ smiling nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ unwell nil)
 (emoji--command-Emoji\ >\ Travel\ &\ Places nil)
 (emoji--command-Emoji\ >\ Travel\ &\ Places\ >\ transport-air nil)
 (emoji--command-Recent nil)
 (emoji-insert nil)
 (gptel-menu nil
             ("g*ChatGPT*"))
 (gptel-system-prompt nil)
 (magit-blame
  ("-w"))
 (magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  (("--" "config/routes.rb")
   "--no-ext-diff" "--stat")
  (("--" "app/assets/stylesheets/responsive/mobile.scss")
   "--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-file-dispatch nil)
 (magit-gitignore nil)
 (magit-log
  ("-n256" "--graph" "--decorate")
  (("--" "./"))
  (("--" "./")
   "--graph")
  ("-n256" "--graph" "--color" "--decorate")
  ("--graph" "--decorate")
  ("-n256"
   ("--" "--")
   "--graph" "--color" "--decorate")
  ("--graph" "--color"))
 (magit-merge nil
              ("--ff-only"))
 (magit-patch nil)
 (magit-patch-create nil)
 (magit-pull nil)
 (magit-push nil
             ("--force"))
 (magit-rebase nil)
 (magit-remote
  ("-f"))
 (magit-reset nil)
 (magit-revert
  ("--edit"))
 (magit-stash nil)
 (magit-status-jump nil)
 (magit:-- "--" "--color" "")
 (transient:gptel-menu:b)
 (transient:gptel-menu:g))
