;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ab/toggle-eshell-visor
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-skip-close-maybe
	beginning-of-buffer
	beginning-of-visual-line
	comment-dwim
	dabbrev-expand
	delete-horizontal-space
	delete-indentation
	dired-toggle-read-only
	end-of-visual-line
	eval-last-sexp
	find-file
	goto-line
	indent-for-tab-command
	js2-mode-show-node
	kill-region
	kill-visual-line
	mark-whole-buffer
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-open-line
	org-self-insert-command
	org-table-blank-field
	org-time-stamp
	org-yank
	outline-next-visible-heading
	set-goal-column
	sgml-slash
	switch-to-buffer
	transpose-words
	view-emacs-debugging
	wdired-finish-edit
	web-mode-comment-or-uncomment
	web-mode-element-wrap
	write-file
	yas-abort-snippet
	yas-expand
	yas-next-field-or-maybe-expand
	))

(setq mc/cmds-to-run-once
      '(
	describe-key
	dired-jump
	help-for-help
	))
