(deftheme webdev
  "Created 2014-09-21, by Andrew Buckingham.")


(custom-theme-set-faces
 'WebDev
 '(default ((t (:family "Menlo" :foundry "apple" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "gray" :background "black" :stipple nil :inherit nil))))
 '(cursor ((t (:background "Yellow"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#b2baf6"))))
 '(highlight ((t (:background "Red" :inverse-video nil))))
 '(region ((t (:background "alternateSelectedControlColor"))))
 '(shadow ((t (:foreground "scrollBarColor"))))
 '(secondary-selection ((t (:background "#222"))))
 '(trailing-whitespace ((t (:underline nil :background "red"))))
 '(font-lock-builtin-face ((t (:foreground "#b2baf6"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#f6df92" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#efc334"))))
 '(font-lock-constant-face ((t (:foreground "#3aff83"))))
 '(font-lock-doc-face ((t (:foreground "#c350ff" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#f09fff"))))
 '(font-lock-keyword-face ((t (:foreground "#5af2ee"))))
 '(font-lock-negation-char-face ((t (:foreground "#acfb5a"))))
 '(font-lock-preprocessor-face ((t (:foreground "#d020a7" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#5af2ee" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#c350ff" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#ff5f87"))))
 '(font-lock-type-face ((t (:foreground "#b2baf6"))))
 '(font-lock-variable-name-face ((t (:foreground "#f6df92"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "red" :inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#3affa3"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#222"))))
 '(header-line ((t (:box nil :foreground "#c350ff" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#eee" :background "#331133"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#f6df92"))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#c350ff"))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box nil :foreground "#643" :background "#110011" :inherit (mode-line)))))
 '(isearch ((t (:inverse-video t :foreground "#f6df92" :background "black"))))
 '(isearch-fail ((t (:inverse-video t :background "black" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#5af2ee" :background "black"))))
 '(match ((t (:inverse-video t :foreground "#b2baf6" :background "black"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'WebDev)
